### ISSUE TITLE
metadata.db not created and not filled

### ISSUE THREAD

**Issue by DracoMilesX** [linuxserver/docker-cops#9]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

XPEnology DSM 6.0.2-8451 Update 5

docker create \
    --name=cops \
    -v /volume4/Drive4/Apps/cops:/config \
    -v /volume1/Drive/Books:/books \
    -e TZ=Europe/Amsterdam \
    -p 80:80 \
    linuxserver/cops

> [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
> [s6-init] ensuring user provided files have correct perms...exited 0.
> [fix-attrs.d] applying ownership & permissions fixes...
> [fix-attrs.d] done.
> [cont-init.d] executing container initialization scripts...
> [cont-init.d] 10-adduser: executing...
> usermod: no changes
> 
> -------------------------------------
>           _     _ _
>          | |___| (_) ___
>          | / __| | |/ _ \
>          | \__ \ | | (_) |
>          |_|___/ |_|\___/
>                |_|
> 
> Brought to you by linuxserver.io
> We gratefully accept donations at:
> https://www.linuxserver.io/index.php/donations/
> -------------------------------------
> GID/UID
> -------------------------------------
> User uid:    911
> User gid:    911
> -------------------------------------
> 
> [cont-init.d] 10-adduser: exited 0.
> [cont-init.d] 20-config: executing...
> [cont-init.d] 20-config: exited 0.
> [cont-init.d] 30-keygen: executing...
> generating self-signed keys in /config/keys, you can replace these with your own                                                                                                                                keys if required
> Generating a 2048 bit RSA private key
> ........+++
> ................................................................................                                                                                                                               ............................+++
> writing new private key to '/config/keys/cert.key'
> -----
> Subject Attribute /C has no known NID, skipped
> [cont-init.d] 30-keygen: exited 0.
> [cont-init.d] 40-config: executing...
> rm: cannot remove '/var/www/localhost/cops/config_local.*.php': No such file or                                                                                                                                directory
> [cont-init.d] 40-config: exited 0.
> [cont-init.d] done.
> [services.d] starting services
> [services.d] done.

Nop

DB creation needs to be added?

##  Thanks, team linuxserver.io

Edit: Don't mind my shitty github formatting.

As well a small question where can I ask docker requests for other services? Noticed the forum is kinda death.

**Comment by sparklyballs** [comment]
that's perfectly normal.

you don't create the database with this docker, you supply the path to an existing calibre database
